import 'package:get/get.dart';

class Translates extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'devices':'devices',
          'light':'Light',
          'temperature':'Temperature',
          'shutters': 'Shutters',
          'scenarios': 'Scenarios',
          'manage_scenarios': 'Manage Scenarios',
          'home': 'Home',
          'security': 'Security',
          'settings': 'Settings',
          'slide_to_scenario': 'Side to do',
          't0':'Floor 0',
          't1':'Floor 1',
          't2':'Floor 2',
          't3' :'Floor 3',
          't4' :'Floor 4',
          't5' :'Floor -1',
          't6' :'Floor -2',
          't7' :'Roof top',
          't8' :'Yard',
          't9' :'Janitor',
          't10': 'Nama',
          'A': 'paziraie',
          'B': 'neshiman',
          'C': 'ashpazkhane',
          'D': 'Matbakh',
          'E': 'khab',
          'F': 'rahro',
          'G': 'teras',
          'H': 'laundry',
          'I': 'rahPele',
          'J': 'hamam',
          'K': 'toilet',
          'L': 'ehzarAsansor',
          'M': 'iphoneTasviri',
          'N': 'motorkhane',
          'O': 'majmooeAbi',
          'P': 'anbari',
          'Q': 'alachigh',
          'a': 'Luster',
          'b': 'Halogen',
          'c': 'Wall hanging',
          'd': 'Secret light',
          'e': 'Liner',
          'f': 'Pendant',
          'g': 'Ventilator',
          'h': 'Moonlight',
          'i': 'Projector',
          'j': 'Burial light',
          'k': 'Headlight',
          'l': 'Park light',
          'm': 'Electric faucet',
          'n': 'Pomp',
          'o': 'Motor',
          'p': 'Electric curtain',
          'q': 'Roll up shutter',
          'r': 'Electric door',
          's': 'Air conditioner',
          't': 'Water cooler',
          'u': 'Fan quel',
          'v': 'Door opener',
          'w': 'Package',
          'enter': 'Enter',
          'exit': 'Exit',
          'locations':'Locations',
          'change_username': 'Change username',
          'logout':'Logout',
          'logout_message': 'Are your sure?',
          'new_location': 'Define new location',
          'name_':'Name:',
          'save':'Save',
          'new_location_saved':'New location added',
          'connect': 'connect',
          'edit': 'Edit',
          'delete': 'Delete',
          'location_info':'Location info',
          'location_name': 'Location name',
          'direct_connection':'Direct connection',
          'modem_connection': 'Modem connection',
          'mac_address': 'Mac address',
          'modem_name': 'Model name',
          'scenario_name': 'Scenario name',
          'modem_password': 'Model password',
          'modem_ip': 'ip on modem',
          'static_ip': 'Static ip',
          'location_settings': 'Location settings',
          'cancel': "Cancel",
          'call_elevator': 'Call elevator',
          'goto_main': 'Go Main screen',
          'error_not_found_device':'Device not found. Please check the connections and try again',
          'try_again': 'Try Again',
          'create_scenario': 'Create scenario',

        },
        'fa_IR': {
          'devices':'دستگاه',
          'light':'روشنایی',
          'temperature':'دما',
          'shutters': 'پرده کرکره',
          'scenarios': 'سناریوها',
          'manage_scenarios': 'مدیریت سناریوها',
          'home': 'خانه',
          'security': 'امنیت',
          'settings': 'تنظیمات',
          'slide_to_scenario': 'بکشید تا اجرا شود',
          't0' :'همکف',
          't1' :'طبقه اول',
          't2' :'طبقه دوم',
          't3' :'طبقه سوم',
          't4' :'طبقه چهارم',
          't5' :'طبقه منفی یک',
          't6' :'طبقه منفی دو',
          't7' :'پشت بام',
          't8' :'حیاط',
          't9' :'سرایداری',
          't10': 'نما',
          'A': 'پذیرایی',
          'B': 'نشیمن',
          'C': 'آشپزخانه',
          'D': 'مطبخ',
          'E': 'خواب',
          'F': 'راهرو',
          'G': 'تراس',
          'H': 'لاندری',
          'I': 'راه پله',
          'J': 'حمام',
          'K': 'توالت',
          'L': 'احزار آسانسور',
          'M': 'آیفون تصویری',
          'N': 'موتورخانه',
          'O': 'مجموعه آبی',
          'P': 'انباری',
          'Q': 'آلاچیق',
          'a': 'لوستر',
          'b': 'هالوژن',
          'c': 'دیوارکوب',
          'd': 'نور مخفی',
          'e': 'لاینر',
          'f': 'آویز',
          'g': 'هواکش',
          'h': 'مهتابی',
          'i': 'پروژکتور',
          'j': 'چراغ دفنی',
          'k': 'چراغ نما',
          'l': 'چراغ پارکی',
          'm': 'شیر برقی',
          'n': 'پمپ',
          'o': 'موتور',
          'q': 'کرکره رول آپ',
          'p': 'پرده برقی',
          'r': 'درب برقی',
          's': 'کولر گازی',
          't': 'کولر آبی',
          'u': 'فن کویل',
          'v': 'درب بازکن',
          'w': 'پکیج',
          'enter': 'ورود',
          'exit': 'خروج',
          'locations':'مکان ها',
          'change_username': 'تغییر نام کاربری',
          'logout':'پاک کردن تمام اطلاعات',
          'logout_message': 'با خروج از برنامه کلیه اطلاعات از جمع دستگاه ها و سناریوها حذف خواهند شد. آیا اطمینان دارید؟',
          'new_location': 'تعریف مکان جدید',
          'name_':'نام:',
          'save':'ذخیره',
          'new_location_saved':'مکان جدید اضافه شد',
          'connect': 'متصل',
          'edit': 'ویرایش',
          'delete': 'حذف',
          'location_info':'مشخصات مکان',
          'location_name': 'نام مکان',
          'direct_connection':'اتصال مستقیم',
          'modem_connection': 'اتصال مودم',
          'mac_address': 'مک آدرس',
          'modem_name': 'نام مودم',
          'scenario_name': 'نام سناریو',
          'modem_password': 'پسورد مودم',
          'modem_ip': 'آی پی روی مودم',
          'static_ip': 'آی پی استاتیک',
          'location_settings': 'تنظیمات مکان',
          'cancel': "انصراف",
          'call_elevator': 'احضار آسانسور',
          'goto_main': 'رفتن به صفحه اصلی',
          'error_not_found_device':'دستگاه پیدا نشد. لطفا اتصالات را بررسی و دوباره تلاش نمایید',
          'error_gps':'برای اتصال نیاز به GPS است . لطفا روشن کنید و دوباره تلاش کنید',
          'try_again': 'تلاش دوباره',
          'open_gps': 'بازکردن تنظیمات',
          'create_scenario': ' سناریو جدید',

        }
      };
}
